// https://www.mockaroo.com/
export default {
  results: [
    {
      id: 1,
      user: { title: "Mrs", first_name: "Clemente", last_name: "Reeders" },
      email: "creeders0@businessinsider.com",
      gender: "Female",
      ip_address: "171.201.221.31",
      year: 1984,
      sales: "169494.46",
      country: "Philippines",
      currency: "Peso",
      color: "Red",
    },
    {
      id: 2,
      user: { title: "Honorable", first_name: "Benton", last_name: "Sprowle" },
      email: "bsprowle1@ihg.com",
      gender: "Female",
      ip_address: "155.236.170.68",
      year: 1986,
      sales: "512449.57",
      country: "Russia",
      currency: "Ruble",
      color: "Puce",
    },
    {
      id: 3,
      user: { title: "Mr", first_name: "Randa", last_name: "Pooley" },
      email: "rpooley2@behance.net",
      gender: "Female",
      ip_address: "204.85.73.143",
      year: 1992,
      sales: "366220.81",
      country: "Mexico",
      currency: "Peso",
      color: "Indigo",
    },
    {
      id: 4,
      user: { title: "Dr", first_name: "Kyrstin", last_name: "Trobey" },
      email: "ktrobey3@earthlink.net",
      gender: "Agender",
      ip_address: "32.163.42.147",
      year: 2006,
      sales: "915386.08",
      country: "China",
      currency: "Yuan Renminbi",
      color: "Orange",
    },
    {
      id: 5,
      user: { title: "Mrs", first_name: "Austine", last_name: "Bugge" },
      email: "abugge4@theguardian.com",
      gender: "Male",
      ip_address: "126.97.157.149",
      year: 2011,
      sales: "548918.39",
      country: "Denmark",
      currency: "Krone",
      color: "Teal",
    },
    {
      id: 6,
      user: { title: "Mr", first_name: "Talyah", last_name: "Praundlin" },
      email: "tpraundlin5@cam.ac.uk",
      gender: "Male",
      ip_address: "9.233.25.185",
      year: 2009,
      sales: "907582.16",
      country: "Indonesia",
      currency: "Rupiah",
      color: "Yellow",
    },
    {
      id: 7,
      user: { title: "Mr", first_name: "Trueman", last_name: "Matijevic" },
      email: "tmatijevic6@ezinearticles.com",
      gender: "Agender",
      ip_address: "198.47.45.183",
      year: 2000,
      sales: "101140.22",
      country: "Poland",
      currency: "Zloty",
      color: "Blue",
    },
    {
      id: 8,
      user: { title: "Dr", first_name: "Darcy", last_name: "Domsalla" },
      email: "ddomsalla7@usda.gov",
      gender: "Female",
      ip_address: "153.69.52.127",
      year: 2002,
      sales: "965458.53",
      country: "France",
      currency: "Euro",
      color: "Teal",
    },
    {
      id: 9,
      user: { title: "Mr", first_name: "Eden", last_name: "Grassot" },
      email: "egrassot8@mac.com",
      gender: "Male",
      ip_address: "166.199.220.230",
      year: 2010,
      sales: "304045.97",
      country: "Sweden",
      currency: "Krona",
      color: "Crimson",
    },
    {
      id: 10,
      user: { title: "Ms", first_name: "Gawain", last_name: "Longlands" },
      email: "glonglands9@live.com",
      gender: "Genderqueer",
      ip_address: "41.173.135.18",
      year: 1995,
      sales: "234024.33",
      country: "China",
      currency: "Yuan Renminbi",
      color: "Aquamarine",
    },
    {
      id: 11,
      user: { title: "Mr", first_name: "Ethelin", last_name: "McQuaker" },
      email: "emcquakera@walmart.com",
      gender: "Agender",
      ip_address: "44.76.59.253",
      year: 1997,
      sales: "145502.68",
      country: "Japan",
      currency: "Yen",
      color: "Pink",
    },
    {
      id: 12,
      user: { title: "Dr", first_name: "Enrique", last_name: "Marciskewski" },
      email: "emarciskewskib@soup.io",
      gender: "Polygender",
      ip_address: "19.7.22.53",
      year: 1996,
      sales: "714951.89",
      country: "Colombia",
      currency: "Peso",
      color: "Turquoise",
    },
    {
      id: 13,
      user: { title: "Rev", first_name: "Theodor", last_name: "Denford" },
      email: "tdenfordc@mapquest.com",
      gender: "Agender",
      ip_address: "35.231.217.71",
      year: 1996,
      sales: "626982.89",
      country: "Russia",
      currency: "Ruble",
      color: "Maroon",
    },
    {
      id: 14,
      user: { title: "Honorable", first_name: "Mindy", last_name: "Bartalini" },
      email: "mbartalinid@indiatimes.com",
      gender: "Polygender",
      ip_address: "248.20.111.13",
      year: 2010,
      sales: "542880.59",
      country: "Sweden",
      currency: "Krona",
      color: "Red",
    },
    {
      id: 15,
      user: { title: "Rev", first_name: "Katharine", last_name: "Maciaszczyk" },
      email: "kmaciaszczyke@furl.net",
      gender: "Female",
      ip_address: "148.22.54.35",
      year: 1996,
      sales: "756964.42",
      country: "Russia",
      currency: "Ruble",
      color: "Blue",
    },
    {
      id: 16,
      user: { title: "Ms", first_name: "Barton", last_name: "Aronowitz" },
      email: "baronowitzf@xrea.com",
      gender: "Female",
      ip_address: "9.58.165.9",
      year: 1994,
      sales: "911207.62",
      country: "Ukraine",
      currency: "Hryvnia",
      color: "Pink",
    },
    {
      id: 17,
      user: { title: "Dr", first_name: "Ileana", last_name: "Hoggetts" },
      email: "ihoggettsg@hexun.com",
      gender: "Male",
      ip_address: "20.115.43.109",
      year: 2006,
      sales: "884321.16",
      country: "Venezuela",
      currency: "Bolivar",
      color: "Khaki",
    },
    {
      id: 18,
      user: { title: "Honorable", first_name: "Annette", last_name: "Knobell" },
      email: "aknobellh@wordpress.org",
      gender: "Polygender",
      ip_address: "49.116.131.29",
      year: 2007,
      sales: "82909.67",
      country: "Bolivia",
      currency: "Boliviano",
      color: "Red",
    },
    {
      id: 19,
      user: { title: "Honorable", first_name: "Laurette", last_name: "Bliben" },
      email: "lblibeni@squarespace.com",
      gender: "Male",
      ip_address: "77.116.255.58",
      year: 1959,
      sales: "695449.43",
      country: "Indonesia",
      currency: "Rupiah",
      color: "Red",
    },
    {
      id: 20,
      user: { title: "Dr", first_name: "Padraig", last_name: "Fayerbrother" },
      email: "pfayerbrotherj@friendfeed.com",
      gender: "Female",
      ip_address: "80.63.108.4",
      year: 1989,
      sales: "236098.27",
      country: "Indonesia",
      currency: "Rupiah",
      color: "Crimson",
    },
    {
      id: 21,
      user: { title: "Ms", first_name: "Mitchael", last_name: "Tschersich" },
      email: "mtschersichk@last.fm",
      gender: "Polygender",
      ip_address: "214.228.177.215",
      year: 1993,
      sales: "147647.06",
      country: "Japan",
      currency: "Yen",
      color: "Yellow",
    },
    {
      id: 22,
      user: { title: "Honorable", first_name: "Riley", last_name: "Sickling" },
      email: "rsicklingl@hao123.com",
      gender: "Agender",
      ip_address: "205.158.41.130",
      year: 1993,
      sales: "287113.27",
      country: "Norway",
      currency: "Krone",
      color: "Puce",
    },
    {
      id: 23,
      user: { title: "Mrs", first_name: "Aguistin", last_name: "Lantoph" },
      email: "alantophm@com.com",
      gender: "Female",
      ip_address: "189.173.241.19",
      year: 2005,
      sales: "532326.27",
      country: "Thailand",
      currency: "Baht",
      color: "Mauv",
    },
    {
      id: 24,
      user: { title: "Rev", first_name: "Aguste", last_name: "Licquorish" },
      email: "alicquorishn@cdc.gov",
      gender: "Male",
      ip_address: "136.160.25.5",
      year: 2012,
      sales: "747366.66",
      country: "Peru",
      currency: "Sol",
      color: "Violet",
    },
    {
      id: 25,
      user: { title: "Mrs", first_name: "Irita", last_name: "Cancelier" },
      email: "icanceliero@unesco.org",
      gender: "Genderqueer",
      ip_address: "218.104.90.84",
      year: 2002,
      sales: "762828.60",
      country: "China",
      currency: "Yuan Renminbi",
      color: "Green",
    },
  ],
};
